# API
FROM python:3.11

WORKDIR /app

# Install pandoc and libreoffice
RUN apt-get update && \
    apt-get install -y pandoc libreoffice && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5059

CMD ["gunicorn", "-b", "0.0.0.0:5059", "app:app"]
# CMD ["gunicorn", "-b", "0.0.0.0:5059", "--log-level", "debug", "--reload", "app:app"]